# Analisis estatico: conflictos, redundancia y reglas potencialmente inactivas
from ast_nodes import And, Comparison, Fact


# pasa una condicion a texto para poder compararla
def condicion_str(cond):
    if isinstance(cond, And):
        return condicion_str(cond.left) + " AND " + condicion_str(cond.right)
    elif isinstance(cond, Comparison):
        return cond.identifier + " " + cond.operator + " " + str(cond.value)
    elif isinstance(cond, Fact):
        return cond.identifier
    return ""


# guarda en la lista los hechos que aparecen en una condicion
def hechos_de_condicion(cond, lista):
    if isinstance(cond, And):
        hechos_de_condicion(cond.left, lista)
        hechos_de_condicion(cond.right, lista)
    elif isinstance(cond, Fact):
        lista.append(cond.identifier)


# revisa si una condicion podria llegar a ser verdadera alguna vez
def es_satisfacible(cond, variables, hechos_posibles):
    if isinstance(cond, And):
        return es_satisfacible(cond.left, variables, hechos_posibles) and es_satisfacible(cond.right, variables, hechos_posibles)
    elif isinstance(cond, Comparison):
        if cond.identifier not in variables:
            return True
        valor = variables[cond.identifier]
        if cond.operator == ">":
            return valor > cond.value
        elif cond.operator == "<":
            return valor < cond.value
        elif cond.operator == "=":
            return valor == cond.value
        return False
    elif isinstance(cond, Fact):
        return cond.identifier in hechos_posibles
    return True


def analizar(programa, variables, hechos_iniciales):
    mensajes = []
    reglas = programa.rules

    # conflictos: una misma accion generada por reglas con condiciones distintas
    acciones = {}
    for regla in reglas:
        a = regla.action.identifier
        if a not in acciones:
            acciones[a] = []
        acciones[a].append(regla)
    for a in acciones:
        grupo = acciones[a]
        if len(grupo) >= 2:
            condiciones = []
            for r in grupo:
                c = condicion_str(r.condition)
                if c not in condiciones:
                    condiciones.append(c)
            if len(condiciones) >= 2:
                nombres = []
                for r in grupo:
                    nombres.append(r.name)
                mensajes.append("Action " + a + " generated by " + ", ".join(nombres))

    # redundancia: dos reglas con la misma condicion y la misma accion
    for i in range(len(reglas)):
        for j in range(i + 1, len(reglas)):
            r1 = reglas[i]
            r2 = reglas[j]
            if condicion_str(r1.condition) == condicion_str(r2.condition) and r1.action.identifier == r2.action.identifier:
                mensajes.append("Redundant rules: " + r1.name + ", " + r2.name)

    # reglas inactivas: la condicion nunca puede ser verdadera, la accion no la
    # usa ninguna otra regla y el programa si tiene otras reglas que si sirven
    hechos_posibles = set(hechos_iniciales)
    for regla in reglas:
        hechos_posibles.add(regla.action.identifier)
    acciones_usadas = []
    for regla in reglas:
        hechos_de_condicion(regla.condition, acciones_usadas)
    for regla in reglas:
        if not es_satisfacible(regla.condition, variables, hechos_posibles):
            if regla.action.identifier not in acciones_usadas:
                hay_otra_activa = False
                for otra in reglas:
                    if otra is not regla and es_satisfacible(otra.condition, variables, hechos_posibles):
                        hay_otra_activa = True
                if hay_otra_activa:
                    mensajes.append("Potentially inactive rule: " + regla.name)

    return mensajes
